---
- hosts: localhost
  vars: 
      install_drive: /dev/sda
      efi_partition: /dev/sda1
      system_partition: /dev/sda2
      hostname: duckbox
      timezone: America/Sao_Paulo
  tasks:
    - name: Abort if the host is not booted from the Arch install media
      fail:
        msg: "This host is not booted from the Arch install media!"
      when: ansible_nodename != 'archiso'
      tags:
        - quick_exit
    - name: Load my keyboard Layout
      command: loadkeys br-abnt2
    - name: Synchronize clock via NTP
      command: timedatectl set-ntp true
      tags:
        - sync_clock
    - name: Wipe all partitions
      command: wipefs --force --all "{{install_drive}}"
      tags:
        - wipefs
    - name: Zap all partitions
      command: sgdisk -Z "{{install_drive}}"
      tags:
        - sgdisk


    - name: Create EFI partitions
      community.general.parted:
        device: "{{install_drive}}"
        number: 1
        state: present
        fs_type: fat32    

