---
- hosts: localhost
  become: yes
  tasks:
  - name: Find Current Dir 
    shell: pwd
    register: current_dir
  - debug: var=current_dir.stdout

   - name: Get Username 
    shell: whoami
    register: username
  - debug: var=username.stdout
   

  - name: Create the 'aur_builder' user
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the 'aur_builder' user to run 'sudo pacman' without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'ãur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: /etc/pacman.conf (Color)
    ansible.builtin.lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: 'Color'

  - name: /etc/pacman.conf (ILoveCandy)
    ansible.builtin.lineinfile:
      path: /etc/pacman.conf
      regexp: '^#NoProgressBar'
      line: 'ILoveCandy'


  # Note: Dependency resolution will still include repository packages.
  - name: Upgrade the system using paru
    kewlfft.aur.aur:
      upgrade: yes
      use: paru
      aur_only: no
    become: yes
    become_user: aur_builder
  # Skip if it is already installed
  - name: Installing xorg, zramd,ntp and cronie
    kewlfft.aur.aur:
      name: 
        - xorg
        - zramd
        - ntp
        - cronie
      use: paru
      state: present
    become: yes
    become_user: aur_builder

  - name: /etc/default/zramd (1)
    ansible.builtin.lineinfile:
      path: /etc/default/zramd
      regexp: '^# ALGORITHM=zstd'
      line: 'ALGORITHM=zstd'


  - name: /etc/default/zramd (2)
    ansible.builtin.lineinfile:
      path: /etc/default/zramd
      regexp: '^# MAX_SIZE=8192'
      line: 'MAX_SIZE=512'

  - name: /etc/default/zramd (3)
    ansible.builtin.lineinfile:
      path: /etc/default/zramd
      regexp: '^# NUM_DEVICES=1'
      line: 'NUM_DEVICES=1'

  - name: Enable zramd
    ansible.builtin.systemd:
      name: zramd.service
      state: started
      enabled: yes


  - name: Enable cronie
    ansible.builtin.systemd:
      name: cronie.service
      state: started
      enabled: yes

  - name: Config ntp
    shell: |
      sudo timedatectl set-ntp true
      sudo timedatectl set-ntp on

  - name: Enable ntp
    ansible.builtin.systemd:
      name: ntpd.service
      state: started
      enabled: yes
     
  - name: Config xorg Keyboard
    ansible.builtin.copy:
      src: "{{current_dir.stdout}}/00-keyboard.conf"
      dest: /etc/X11/xorg.conf.d/
      follow: no

  - name: Blacklist i2c nvidia
    ansible.builtin.copy:
      src: "{{current_dir.stdout}}/blacklist_i2c-nvidia-gpu.conf"
      dest: /etc/modprobe.d/
      follow: no


  - name: Install Kernel TKG Cacule
    kewlfft.aur.aur:
      name: 
        - linux-tkg-cacule
        - linux-tkg-cacule-headers
        - nvidia-dkms
        - nvidia-utils 
        - nvidia-settings
        - grub-customizer
        - bspwm
        - sxhkd
        - picom
        - feh
        - scrot
        - wget
        - mpd
        - dunst
        - libfm
        - lxappearance
        - xfce4-appfinder
        - xfce4-panel
        - xfce4-power-manager
        - xfce4-session
        - xfce4-settings
        - xfce4-terminal
        - xorg-fonts-misc
        - adapta-gtk-theme
        - papirus-icon-theme
        - alacritty
        - thunar
        - raw-thumbnailer
        - thunar-archive-plugin
        - thunar-media-tags-plugin
        - thunar-volman
        - tumbler
        - ffmpegthumbnailer
        - pipewire
        - pipewire-alsa
        - pipewire-pulse
        - pipewire-jack
        - pavucontrol
        - ttf-fira-code
        - noto-fonts
        - ttf-roboto
        - leafpad
        - neofetch
        - firefox
        - parted
        - exa
        - qpdfview
        - curl
        - gimp
        - gthumb
        - flameshot
        - bpytop
        - speedcrunch
        - gvfs
        - vlc
        - hugo
        - libfido2
        - zoxide
        - python-pygments
        - seahorse
        - yad
        - qt5-styleplugins
        - nerd-fonts-iosevka
        - nerd-fonts-meslo
        - siji-git
        - ttf-unifont
        - ttf-dejavu
        - ttf-meslo-nerd-font-powerlevel10k
        - polybar
        - i3lock-color
        - xfce-polkit
        - ulauncher
        - google-chrome
        - chroma-bin
        - vifm-git
        - vifmimg-git
        - vifm-colors-git
        - vifm-devicons-git
        - vim-vifm-git
        - kotatogram-desktop-bin
        - megasync 
        - snapper
        - snapper-gui-git
        - snap-pac-grub
        - lxdm
      use: paru
      state: present
    become: yes
    become_user: aur_builder

  - name: /etc/lxdm/lxdm.conf (autologin)
    ansible.builtin.lineinfile:
      path: /etc/lxdm/lxdm.conf
      regexp: '^#autologin.*'
      line: "autologin={{username.stdout}}"


  - name: /etc/lxdm/lxdm.conf (numlock)
    ansible.builtin.lineinfile:
      path: /etc/lxdm/lxdm.conf
      regexp: '^#numlock=.*'
      line: "numlock=1"


  - name: Enable lxdm
    ansible.builtin.systemd:
      name: lxdm.service
      state: stopped
      enabled: yes







