---
- hosts: localhost
  become: yes
  tasks:
  - name: Create the 'aur_builder' user
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the 'aur_builder' user to run 'sudo pacman' without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'ãur_builer ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: /etc/pacman.conf (Color)
    ansible.builtin.lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: 'Color'

  - name: /etc/pacman.conf (ILoveCandy)
    ansible.builtin.lineinfile:
      path: /etc/pacman.conf
      regexp: '^#NoProgressBar'
      line: 'ILoveCandy'

