---
- hosts: localhost
  become: yes
  tasks:
    - name: Find out playbook's path
      shell: pwd
      register: current_dir
    - debug: var=current_dir.stdout


    - name: /etc/default/grub (1)
        ansible.builtin.lineinfile:
          path: /mnt/etc/default/grub
          regexp: '^GRUB_DEFAULT=0'
          line: 'GRUB_DEFAULT=saved'

    - name: /etc/default/grub (2)
        ansible.builtin.lineinfile:
          path: /mnt/etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
         

    - name: /etc/default/grub (3)
      ansible.builtin.lineinfile:
        path: /mnt/etc/default/grub
        regexp: '^#GRUB_SAVEDEFAULT=true'
        line: 'GRUB_SAVEDEFAULT=true'


    - name: /etc/default/grub (4)
      ansible.builtin.lineinfile:
        path: /mnt/etc/default/grub
        regexp: '^#GRUB_DISABLE_SUBMENU=y'
        line: 'GRUB_DISABLE_SUBMENU=y'

    - name: /etc/default/grub (5)
      ansible.builtin.lineinfile:
        path: /mnt/etc/default/grub
        regexp: '^GRUB_GFXMODE=auto'
        line: "GRUB_GFXMODE=\"{{grub_gfx}}\""

    - name: Inserte os-prober line to grub
      blockinfile:
        path: /etc/default/grub
        block: |
          GRUB_DISABLE_OS_PROBER=false

    - name: Install grub Theme - Cyberpunk
      ansible.posix.synchronize:
        src: "{{current_dir.stdout}}/Cyberpunk"
        dest: /boot/grub/themes/
          
    - name: Update grub
      shell: "{{chroot}} grub-mkconfig -o /boot/grub/grub.cfg"
      tags:
        - grub-mkconfig
       
